feature(stage): watch file changes in repository when window is inactive
calahatras/gitout pull request #128
Opened 2021-04-04 19:19 UTC by calahatras

Refresh status and selected file if any change occurs when window is inactive

Solves go-27

2021-04-06 20:58 UTC, mickedefault reviewed
Code looks great! Haven't tested it (I'm on my phone).
I'm wondering if we should make this togglable or present a button to explicitly refresh 🤔 sometimes you might *want* to see how it looked when you last had go open (something like "crap i made a lot of changes here.. and i didn't do a commit like i should have. Go, please show me how it looked before i changed this")

2021-04-06 21:34 UTC, calahatras commented
Yeah, had that first and then just figured this was easier. 😄 
I used a toast/snack to begin with with options for refreshing, I'll see if I can add it again, maybe as an option to autorefresh :+1:

2021-04-10 17:44 UTC, mickedefault requested changes
would love for a setting to always have this set!
I think we need to investigate how visual studio saves files. In my testing I didn't get the refresh button very often, because when determining if it was the current file (i.e. setting `selectedFileHasChanges`) the `args.RepositoryPath` was very often a temporary file, which I guess visual studio created. since it was a "new" file and (perhaps the files are swapped or something) gitout didn't see it as the current file.
![no_refresh_button](https://user-images.githubusercontent.com/38684932/114279271-14085780-9a34-11eb-8d8a-465074cffb93.gif)

2021-04-10 17:44 UTC, mickedefault commented on GitOut/Features/Git/Stage/GitStageViewModel.cs
> +                                if (!(previousCancellation is null))
can be modified after the .net 5 feature

2021-04-10 17:44 UTC, mickedefault commented on GitOut/Features/Git/Stage/GitStageViewModel.cs
> +#pragma warning disable CA1031 // Do not catch general exception types
this triggers a warning on my machine. Let's compare editorconfigs

2021-04-10 17:44 UTC, mickedefault commented on GitOut/Features/Material/Snackbar/Snack.cs
> +            private CancellationToken cancelToken;
Optional:
I prefer `cancellationToken` as a name

2021-04-10 20:45 UTC, calahatras commented
> 
> 
> would love for a setting to always have this set!
> I think we need to investigate how visual studio saves files. In my testing I didn't get the refresh button very often, because when determining if it was the current file (i.e. setting `selectedFileHasChanges`) the `args.RepositoryPath` was very often a temporary file, which I guess visual studio created. since it was a "new" file and (perhaps the files are swapped or something) gitout didn't see it as the current file.
> ![no_refresh_button](https://user-images.githubusercontent.com/38684932/114279271-14085780-9a34-11eb-8d8a-465074cffb93.gif)

Interesting, I did not experience that behavior during development 🤔 If it *is* a temporary file of some kind, there's no real way for us to determine what file it actually should relate to though. It looks like the "real name" shows up with a ~-suffix, do you get multiple events for the same file? I find it strange that FileSystemWatcher doesn't get an event for the real file when that is written to in the end.

2021-04-19 20:30 UTC, mickedefault approved these changes

2021-04-19 20:46 UTC, merged