enhancement(log): show stashes in log view, toggle visibility in view options popover
calahatras/gitout pull request #159
Opened 2021-10-14 19:04 UTC by calahatras

2021-10-27 21:42 UTC, mickedefault requested changes
~unfortunately crashes at the moment when opening a project without stashes.~

2021-10-27 21:42 UTC, mickedefault commented on GitOut/Features/Git/LocalGitRepository.cs
> +                        item.Branches.Add(GitBranchName.CreateLocal($"stash@{{{i}}}"));
can we use the stash reflog selector as the branch name? [git pretty formats](https://git-scm.com/docs/pretty-formats)
>%gD
> reflog selector, e.g., refs/stash@{1} or refs/stash@{2 minutes ago}; [..]
> %gd
> shortened reflog selector; same as %gD, but the refname portion is shortened for human readability (so refs/heads/master becomes just master).

2021-10-27 21:42 UTC, mickedefault commented on GitOut/Features/Git/LogOptions.cs
>      public class LogOptions
can be converted to a record

2021-11-14 20:38 UTC, calahatras commented on GitOut/Features/Git/LocalGitRepository.cs
> +                        item.Branches.Add(GitBranchName.CreateLocal($"stash@{{{i}}}"));
You mean just prefix with `refs/`?

2021-11-14 21:32 UTC, mickedefault commented on GitOut/Features/Git/LocalGitRepository.cs
> +                        item.Branches.Add(GitBranchName.CreateLocal($"stash@{{{i}}}"));
hm. I can't remember why I figured that name would be better. 🤔 
what i was after was the descriptive name (for instance "WIP on <branch>: <description>")

2021-11-15 22:01 UTC, calahatras commented on GitOut/Features/Git/LocalGitRepository.cs
> +                        item.Branches.Add(GitBranchName.CreateLocal($"stash@{{{i}}}"));
WIP on is available with the latest change. I update GitStash to be a subclass of GitLogEntry instead, and read stashes using the same pretty format as logs, which means we get author, dates, and all that jazz as well.

2021-12-05 15:57 UTC, calahatras commented on GitOut/Features/Git/LogOptions.cs
>      public class LogOptions
It is now

2021-12-07 22:03 UTC, mickedefault approved these changes
:star:

2021-12-08 21:52 UTC, merged